version: "3"
services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - t3-network

  postgres:
    image: postgres:10.3
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=nestAuth
      - POSTGRES_PASSWORD=nestAuth
      - POSTGRES_DB=nestAuth
    networks:
      - t3-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - t3-network
volumes:
  postgres:
    name: nest-db

networks:
  t3-network:
