version: "3"
services:
  postgres:
    image: postgres:10.3
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=nestAuth
      - POSTGRES_PASSWORD=nestAuth
      - POSTGRES_DB=nestAuth
    networks:
      - t3-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - t3-network
volumes:
  postgres:
    name: nest-db

networks:
  t3-network:
